<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMaVgeGx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMaVgeGx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMaVgeGx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMaVgeGx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMaVgeGx\App_KernelDevDebugContainer([
    'container.build_hash' => 'MaVgeGx',
    'container.build_id' => '4301665c',
    'container.build_time' => 1610622214,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMaVgeGx');
