<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerODO4Hoz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerODO4Hoz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerODO4Hoz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerODO4Hoz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerODO4Hoz\App_KernelDevDebugContainer([
    'container.build_hash' => 'ODO4Hoz',
    'container.build_id' => '46045b7d',
    'container.build_time' => 1610715266,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerODO4Hoz');
