<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR5roied\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR5roied/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR5roied.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR5roied\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR5roied\App_KernelDevDebugContainer([
    'container.build_hash' => 'R5roied',
    'container.build_id' => '4aa50f09',
    'container.build_time' => 1611942914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR5roied');
